# Install script

We provide an install script at link:../../hack/install.sh[`/hack/install.sh`].

If you're a Homebrew user, see the link:homebrew.adoc[Homebrew setup docs] for a more integrated setup experience.

If you're on Arch Linux, see the link:../../PKGBUILD[PKGBUILD].

## Quick start

If you're feeling lucky, you can install Kharon to `~/.local/bin/` with

[source,shell]
----
export KHARON_INSTALL_DIR=~/.local/bin # <1>
curl -fsSL https://raw.githubusercontent.com/vshn/kharon/refs/heads/main/hack/install.sh | bash
----
<1> The script installs the Kharon binary to the directory given in the `KHARON_INSTALL_DIR` environment variable.
If the variable is unset, the script installs Kharon to `~/.local/bin`.

[NOTE]
====
The install script doesn't modify your `$PATH`.
Either set `KHARON_INSTALL_DIR` to a directory that's already in your `$PATH` or update your `$PATH` before continuing.
====

Afterwards, run `kharon install` to setup the proxy.

Finally, set up your browser as described in the link:browsers.adoc[docs].

## Automated updates with a systemd timer

If you trust us and want automated updates, you can download the script and run it as a systemd timer:

[source,shell]
----
export KHARON_INSTALL_DIR=~/.local/bin # <1>

curl -fsSLo "${KHARON_INSTALL_DIR}/kharon-update.sh" \
  https://raw.githubusercontent.com/vshn/kharon/refs/heads/main/hack/install.sh
chmod +x "${KHARON_INSTALL_DIR}/kharon-update.sh"

cat >~/.config/systemd/user/kharon-update.service <<EOF
[Unit]
Description=Kharon updater

[Service]
Type=oneshot
Environment=KHARON_INSTALL_DIR=${KHARON_INSTALL_DIR}
ExecStart=${KHARON_INSTALL_DIR}/kharon-update.sh

[Install]
WantedBy=default.target
EOF

cat >~/.config/systemd/user/kharon-update.timer <<EOF
[Unit]
Description=Regularly update Kharon (default: 08:00 every day, persistent)

[Timer]
OnCalendar=*-*-* 08:00:00
AccuracySec=10min
Persistent=true

[Install]
WantedBy=timers.target
EOF

systemctl --user daemon-reload
systemctl --user enable kharon-update.timer
systemctl --user start kharon-update.timer
----
<1> You should set this variable to the directory where you've already installed Kharon or want to install Kharon.
