package cmd

import (
	"context"
	"log/slog"
	"net"
	"os"
	"os/signal"
	"strings"
	"syscall"
	"time"

	"github.com/spf13/cobra"

	"github.com/vshn/kharon/internal/pkg/activation"
	"github.com/vshn/kharon/internal/pkg/cache"
	"github.com/vshn/kharon/internal/pkg/proxy"
)

const defaultProxyAddr = "localhost:12000"

var addr, onDemand, proxyMappingFile string
var onDemandShutdownTimeout time.Duration

const proxyCmdLongDesc = `Start a SOCKS5 proxy server listening for incoming connections and forwards them to the appropriate Kubernetes cluster based on the provided domain to jumphost mapping file.
The proxy supports on-demand activation via launchd or systemd and can automatically shut down after a specified timeout when no active connections are present.

There is an experimental feature to serve a proxy auto-configuration (PAC) file at http://<proxy-address>/proxy.pac that can be used to configure the proxy settings in web browsers.
The PAC file is generated based on the current mapping file and allows direct access to specified domains while routing other traffic through the proxy.
While a static proxy configuration is generally sufficient, the PAC file removes an additional hop for direct access domains.
Browsers don't reload the PAC file that often, some browser restarts might be required if using this feature and the mapping file is updated.

Works on the mapping file generated by the 'update' command, so it does not require access to the Lieutenant API.`

const proxyCmdExample = `# Start the proxy with the default settings
kharon proxy
# Get the proxy.pac file for configuring browser proxy settings
curl http://localhost:12000/proxy.pac

# Start the proxy on a specific address
kharon proxy --addr localhost:13000

# Start the proxy with on-demand activation via launchd and a shutdown timeout of 5 minutes
kharon proxy --on-demand=launchd=MySocket --on-demand-shutdown-timeout=5m

`

func init() {
	RootCmd.AddCommand(proxyCmd)

	flag := proxyCmd.Flags()
	flag.StringVar(&addr, "addr", defaultProxyAddr, "Address to bind the proxy to in the format <host>:<port>. If port is set to 0, a random free port will be used.")
	flag.StringVar(&onDemand, "on-demand", "", "On-demand allows the proxy to start from launchd or systemd when a connection is attempted. Value can be '-on-demand=launchd=<SocketName>' or '-on-demand=systemd=<my-socket.socket>'. The proxy will shut down after the specified timeout when no active connections are present.")
	flag.StringVar(&proxyMappingFile, "mapping-file", proxyMappingFilePath(), "Path to the domain to jumphost mapping file. This file can be generated with the `update` subcommand and should be kept up to date. The proxy will watch for SIGHUP to reload the mapping without restarting.")
	flag.DurationVar(&onDemandShutdownTimeout, "on-demand-shutdown-timeout", 3*time.Minute, "Timeout for shutting down the proxy when no active connections are present in on-demand mode. Zero disables automatic shutdown.")
}

var proxyCmd = &cobra.Command{
	Use:     "proxy",
	Short:   "Start a SOCKS5 proxy server for accessing Kubernetes clusters.",
	Long:    proxyCmdLongDesc,
	Example: proxyCmdExample,
	Run:     runProxy,
}

func runProxy(cmd *cobra.Command, _ []string) {
	slog.Info("What part of trying to connect to Kubernetes clusters is a fucking living?")

	if proxyMappingFile == "" {
		slog.Error("Mapping file path is required", "error", "mapping-file flag is empty and failed to determine default path.")
		os.Exit(1)
	}

	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt)
	defer stop()

	proxy := proxy.Proxy{}

	sighup := make(chan os.Signal, 1)
	signal.Notify(sighup, syscall.SIGHUP)
	defer signal.Stop(sighup)
	go func() {
		for range sighup {
			slog.Info("Received SIGHUP, reloading configuration...")
			if err := proxy.Reload(proxyMappingFile); err != nil {
				slog.Error("Failed to reload configuration", slog.Any("error", err))
			}
		}
	}()

	lp := func() (net.Listener, error) {
		return net.Listen("tcp", addr)
	}
	if onDemand != "" {
		proxy.ShutdownTimeout = onDemandShutdownTimeout

		init, opt, hasOpt := strings.Cut(onDemand, "=")
		switch init {
		case "launchd":
			if !hasOpt {
				slog.Error("launchd on-demand requires a socket name, e.g. '-on-demand=launchd=MySocket'")
				os.Exit(1)
			}
			lp = activation.LaunchdListener(opt)
		case "systemd":
			if !hasOpt {
				slog.Error("systemd on-demand requires a systemd socket unit name, e.g. '-on-demand=systemd=<my-socket.socket>'")
				os.Exit(1)
			}
			lp = activation.SystemdListener(opt)
		default:
			slog.Error("Invalid on-demand initializer, must be 'launchd' or 'systemd'", slog.String("value", init))
			os.Exit(1)
		}
	}

	if err := proxy.Start(ctx, lp, proxyMappingFile); err != nil {
		slog.Error("Failed to start proxy", slog.Any("error", err))
		os.Exit(1)
	}
}

func proxyMappingFilePath() string {
	cd, err := cache.ProxyMappingFilePath()
	if err != nil {
		slog.Warn("Failed to get proxy mapping file path", slog.Any("error", err))
		return ""
	}
	return cd
}
