name: Build

permissions: {}

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  go:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
          - runner: ubuntu-24.04-arm
            target: linux-aarch64
          - runner: ubuntu-24.04
            target: linux-x86_64
          - runner: macos-26
            target: darwin-aarch64
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version-file: 'go.mod'

      - name: Run build
        run: make build
