---
name: Check for Vulnerabilities

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: "0 9 * * 1"

permissions:
  contents: read
  security-events: write

jobs:
  check-for-vulnerabilities:
    name: Check for Vulnerabilities
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version-file: 'go.mod'

      - name: Run govulncheck and save to file
        run: go run golang.org/x/vuln/cmd/govulncheck@latest -format sarif ./... > govulncheck.sarif
        env:
          GOEXPERIMENT: jsonv2

      - name: Upload SARIF File
        uses: github/codeql-action/upload-sarif@8aad20d150bbac5944a9f9d289da16a4b0d87c1e # v4.36.2
        with:
          sarif_file: govulncheck.sarif
          category: govulncheck
